### ISSUE TITLE
Add Contributors section

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#10]
@cabo wrote:

> Let's also add a Contributors section (7322, 4.11.) after that (hmm,
> that's what 7322 says; I'd put it before the acknowledgements, but then
> with the 7322 placement it's close to Authors' addresses) and move the
> inactive authors there; just make it look like the items in the authors'
> addresses.

**Comment by brianraymor** [comment]
@cabo - please provide the list of _inactive_ authors.

**Comment by cabo** [comment]
I believe at this point that would be Teemu and Valik; maybe we should also confirm continued authorship with Bill (Bilhanan).  Everybody else is clearly active (e.g., updates text, takes part in the phone conferences, etc.).
