### ISSUE TITLE
Why is 4.7 titled "Capabilities and Settings examples"?

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#107]
It only has examples of Ping and Pong.
(It would probably help to have an example of an initial CSM exchange.)

**Comment by brianraymor** [comment]
Or perhaps eliminate the examples? I note that RFC7252 does not include Option examples.

**Comment by cabo** [comment]
I'd rather do the work to include an initial CSM exchange.  Just not sure I can get to that tomorrow.
(This kind of example is counter-intimidating — after all the verbiage you see that it is all really very simple...)

**Comment by brianraymor** [comment]
I'm not sure that it was intimidating although I like _counter-intimidating_. It was certainly not a source of confusion during WGLC that then required clarification in examples. I worry about simply adding noise. And if pursued further, we should avoid Default-Uri-Host which would leave Max-Message-Size and Block-wise Transfer.

**Comment by brianraymor** [comment]
I corrected the title in #109. I'm _won't fixing_ the suggestion for CSM examples based on my previous comment. This can be revisited if there's any related confusion during subsequent reviews.
