### ISSUE TITLE
Guidance on malformed / message format errors

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#117]
https://www.ietf.org/mail-archive/web/core/current/msg08357.html - WGLC review by Esko Dijk.

1. In RFC 7252, the Reset message (RST) is also used to deal with certain cases of malformed CoAP messages or incorrect field values. Since the RST message is now removed, I think there should be text on how to deal with these cases. For example in Figure 21 (RFC 7252) the Token value is not recognized which leads to a RST. How should CoAP-over-reliable deal with this case and related cases?  Although the draft suggests that Client (if we take the Fig 21 case) could abort the connection, that sounds rather drastic and unnecessary – the client and server need to keep talking to each other typically. Silently ignoring seems better in that case. And in case the receiver of an 'incorrect' message decides not to abort, what should it do instead – anything normative?
Related cases for CoAP message receivers are:
-          Token not recognized -> could happen in the Figure 21 use case, silently ignore seems best. Or would there be a reason to notify the response sender that the response is not recognized? (RFC 7252 allows to do this at least.)
-          Token Length TKL is wrong (e.g. length is 9 to 15) -> could be sent by a malicious CoAP endpoint, good reason to abort perhaps
-          Code unrecognized (e.g. 1.xx, 3.xx, 0.31 … ) -> could happen if one of the endpoints supports other/newer CoAP features, perhaps abort, or perhaps silently ignore? Possibly malicious endpoint.
Summarizing it seems to me the best to specify a receiver MAY abort the connection and also MUST silently ignore the malformed message. This could be made more explicit in the text.

**Comment by brianraymor** [comment]
~~~~
From RFC7252: 

4.2.  Messages Transmitted Reliably

   ...  A recipient
   MUST either (a) acknowledge a Confirmable message with an
   Acknowledgement message or (b) reject the message if the recipient
   lacks context to process the message properly, including situations
   where the message is Empty, uses a code with a reserved class (1, 6,
   or 7), or has a message format error.  Rejecting a Confirmable
   message is effected by sending a matching Reset message and otherwise
   ignoring it.  The Acknowledgement message MUST echo the Message ID of
   the Confirmable message and MUST carry a response or be Empty (see
   Sections 5.2.1 and 5.2.2).  The Reset message MUST echo the Message
   ID of the Confirmable message and MUST be Empty.  Rejecting an
   Acknowledgement or Reset message (including the case where the
   Acknowledgement carries a request or a code with a reserved class, or
   the Reset message is not Empty) is effected by silently ignoring it.
   More generally, recipients of Acknowledgement and Reset messages MUST
   NOT respond with either Acknowledgement or Reset messages.

~~~~

**Comment by brianraymor** [comment]
https://www.ietf.org/mail-archive/web/core/current/msg08397.html

**My initial instinct would be MUST abort the connection.** Can those with early (but shipping) implementations offer any guidance on how this case is currently being handled? What do others think?

**Comment by brianraymor** [comment]
Could we indicate that CoAP over reliable aborts the connection for any _message format error_ defined in RFC7252 (plus the unrecognized token case)?

https://tools.ietf.org/html/rfc7252#section-3

```
   Token Length (TKL):  4-bit unsigned integer.  Indicates the length of
      the variable-length Token field (0-8 bytes).  Lengths 9-15 are
      reserved, MUST NOT be sent, and MUST be processed as a message
      format error.
```
```
   The absence of the
   Payload Marker denotes a zero-length payload.  The presence of a
   marker followed by a zero-length payload MUST be processed as a
   message format error.
```

https://tools.ietf.org/html/rfc7252#section-3.1

Option Delta:
```
      15:  Reserved for the Payload Marker.  If the field is set to this
         value but the entire byte is not the payload marker, this MUST
         be processed as a message format error.
```

   Option Length: 

```
      15:  Reserved for future use.  If the field is set to this value,
         it MUST be processed as a message format error.
```

https://tools.ietf.org/html/rfc7252#section-4.1

```
   An Empty message has the Code field set to 0.00.  The Token Length
   field MUST be set to 0 and bytes of data MUST NOT be present after
   the Message ID field.  If there are any bytes, they MUST be processed
   as a message format error.
```

**Comment by cabo** [comment]
On 2 Mar 2017, at 03:01, Brian Raymor <notifications@github.com> wrote:
> 
> Could we indicate that CoAP over reliable aborts the connection for any message format error defined in RFC7252 (plus the unrecognized token case)?

Sounds good to me.

Message format error = syntax violation

Unrecognized token = failure of mandatory matching

I’m just trying to think whether there are other “cannot happen”s that need to be on this list.

Grüße, Carsten

**Comment by brianraymor** [comment]
While you're thinking about other "cannot happens" ...

The existing text in the Abort section can be updated to cover this issue in a general way:

```
   One reason for an sender to generate an Abort message is a general
   syntax error in the byte-stream received.  No specific option has
   been defined for this, as the details of that syntax error are best
   left to a diagnostic payload.
```
