### ISSUE TITLE
Should it be coaps+ws instead of coap+wss?

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#12]
Another bike shed, but I think we were trying to make the "communication security is active" part visible as "coaps+...", and we should do it here, too.

**Comment by bsilverajan** [comment]
+1. The original websockets draft used "coap+ws:" and "coap+wss:" URI scheme components to reflect their WebSocket counterparts  "ws:" and "wss:" on ports 80 and 443. However, I believe using "coaps+ws:" (as well as "coaps+tcp:") highlights the use of a secure transport, in this case TLS, better.

**Comment by brianraymor** [comment]
I read coap+wss as coap over secure websockets which is correct. 

Another related question - has any other websocket subprotocol registered new URI(s)?

**Comment by brianraymor** [comment]
Yes. It's unfortunate that we have the +ws and +wss in the names because it introduces a bit of cognitive dissonance for websocket developers. Still, I'm fairly neutral on the issue. You're probably right that consistency with "coaps" is more important in getting readers to think "secure connection".

**Comment by ektrah** [comment]
coaps+ws would be CoAP on top of a (D)TLS layer on top of an unsecured WebSockets connection. I don't think that's what we want.

**Comment by bsilverajan** [comment]
@brianraymor wrote: 

> Another related question - has any other websocket subprotocol registered new URI(s)?

To my knowledge, I've not encountered other web socket subprotocols registering new URI schemes. 

RFC 7118 and draft-pd-dispatch-msrp-websocket embed the usage of WebSocket transport as a parameter in their URIs. However, identifying CoAP resources over alternative transports by using a transport parameter in the URI runs into some challenges, particularly when relative URIs need to be resolved.

**Comment by brianraymor** [comment]
No strong opinions. Discuss at IETF 96.

**Comment by jaimejim** [comment]
No strong consensus at IETF96 either. Show of hands should roughly the same numbers and many abstentions.

**Comment by brianraymor** [comment]
Closing. I think that the current "coap+wss" will create less confusion for websocket developers.

**Comment by cabo** [comment]
I continue to believe the web sockets developers are not the target audience for the URIs.

**Comment by brianraymor** [comment]
https://www.ietf.org/mail-archive/web/core/current/msg08091.html

_coap+wss is the only coaps scheme that doesn't have coaps in the name. I continue to believe that this is a mistake._

After starting at the URI schemes for a day, I'm coming around to Carsten's POV. The "coaps" prefix is more consistent.

**Comment by bsilverajan** [comment]
Coming back from my vacation. This is a welcome amendment. This provides enough consistency for me to resume guidelines for the URI format for alternative transports in draft-silverajan-core-coap-alternative-transports
