### ISSUE TITLE
Clarify the description of BERT block size

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#143]
As raised on the [mailing list](https://www.ietf.org/mail-archive/web/core/current/msg08671.html):

[Proposal](https://www.ietf.org/mail-archive/web/core/current/msg08674.html)
_[JLS] I think I now understand what this text is supposed to be saying._

```
"except that the payload is also allowed to contain multiple blocks.
For non-final BERT blocks, the payload is always a multiple of 1024 bytes. 
For final BERT blocks, the payload is a multiple (possibly 0) of 1024 bytes
plus a  partial block of less than 1024 bytes."
```

**Comment by hannestschofenig** [comment]
I agree. This wording is much cleaner.
