### ISSUE TITLE
Alternative address doesn't add state to the new connection

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#144]
Jim Schaad [said](https://www.ietf.org/mail-archive/web/core/current/msg08689.html):

```
I also wanted to be sure that there was no intention that if a release w/ an
alternative address is sent, there is no intention that any state would be
transferred between to the new connection.  
```

We could be explicit that there is no such intention beyond giving an address where the new connection could be established.

**Comment by hannestschofenig** [comment]
Fine for me as well. We have not had such a use case so far where this state transfer would be needed. If one emerges in the future we can always revise the document and add support for it.
