### ISSUE TITLE
Maximum size and Max-Message-Size

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#15]
Capturing embedded issues in #2:

_[I-D.ietf-core-block] uses a message size of maximum 1024 bytes and this specification extends this maximum size to 1024 KiB (= 1 MiB) by re-interpreting the length information._  

@cabo wrote:
1 MiB is an arbitrary limit.  This will be fixed if we have something like Max-Message-Size in the signalling draft.

**Comment by cabo** [comment]
Oh. This sentence is not true.  Block has a **block** size of 1024 bytes max; the messages resulting are likely to be larger.  BERT allows to include slices that are more than one of those 1024-byte blocks.  I have no idea where the arbitrary 1 MiB size is coming from; this needs to go away.

**Comment by brianraymor** [comment]
The offending statement was cut in the merge.
