### ISSUE TITLE
Should there be a mandatory exchange of CSM messages after connection setup?

### ISSUE THREAD

**Issue by cabo** [core-wg/coap-tcp-tls#16]
Michel Veillette points out that a peer that wants to use a new connection has an uncertainty whether a CSM message with capability indications will come or not, so it is hard to decide when to send the first request (either based on default capabilities or waiting for the CSM to come in).  One way out of having to do arbitrary waits would be to *require* the exchange of a CSM message (even an option-less one) after connection setup.  The burden is very low, as a minimal implementation would just need to send a constant message of 0x00 0xe1 at setup.

This requirement could be stated without giving a sequence, effectively allowing both sides to send the initial CSM in parallel, or it could give the listener the opportunity to not send its CSM until the connection opener has sent theirs, trying to avoid the need to answer right away to a connection setup -- this makes it too easy to scan for ports (OK, we also have a default port, and making scanning harder does not by itself provide any security, but it sure makes life a little harder for the attacker).  (To avoid deadlock, the connection opener would not have the opportunity to wait sending the CSM.)

**Comment by brianraymor** [comment]
+1 ... especially for Maximum-Message-Size.

HTTP/2 has a similar flow for SETTINGS during connection including _potentially empty_ settings:

https://tools.ietf.org/html/rfc7540#section-3.5
https://tools.ietf.org/html/rfc7540#section-6.5

**Comment by brianraymor** [comment]
No objections. I will create a pull request for review by the WG.
