### ISSUE TITLE
Parsing of Option numbers for Signaling messages 

### ISSUE THREAD

**Issue by hannestschofenig** [core-wg/coap-tcp-tls#176]
draft-ietf-core-coap-tcp-tls-09#section-5.2 says: 
"
   Option numbers for Signaling messages are specific to the message
   code.  They do not share the number space with CoAP options for
   request/response messages or with Signaling messages using other
   codes.
"

Using a separate space makes sense to avoid confusion with ordinary CoAP usage but is convenient from a parsing point of view since the parser now also needs to take the message type into account rather than just looking at the CoAP option itself. 

Should we re-think this design and to put the CoAP Signal Option Codes from Table 2 in the regular CoAP option space?

**Comment by brianraymor** [comment]
_... but is convenient ..._

inconvenient?

**Comment by hannestschofenig** [comment]
yes, inconvenient. 

The corrected paragraph is: 

Using a separate space makes sense to avoid confusion with ordinary CoAP usage but is inconvenient from a parsing point of view since the parser now also needs to take the message type into account rather than just looking at the CoAP option itself.

**Comment by cabo** [comment]
Actually, it's not the parser (that is unchanged) but the process that assigns semantics to the option numbers just parsed.  While this now does require one additional parameter, this is not really a surprise — this little addition in complexity was known when we designed it.  There is no obvious way to improve this without impinging on the option space for requests/responses — and it is TCP that should pay for the feature here, not UDP.  So I don't think this should be changed in any way at this late stage.

**Comment by brianraymor** [comment]
@hannestschofenig - If you have no objections, I'll close this on 8/25. It does not meet the current bar.
