### ISSUE TITLE
Naming inconsistency for Block-wise Transfer option

### ISSUE THREAD

**Issue by chrysn** [core-wg/coap-tcp-tls#189]
The Block-wise Transfer option of CSMs is called "Block-wise Transfer" in the title of section 5.3.2, its table and text, but "Block-wise-Transfer" (dash instead of space) in the IANA considerations of 11.2.

(Sorry for the late input, but this might be still fixable at the editor stage).

**Comment by cabo** [comment]
Thanks for pointing this out -- please check if this fix changes all necessary occurrences

**Comment by chrysn** [comment]
On Wed, Dec 13, 2017 at 01:48:15PM -0800, cabo wrote:
> please check if this fix changes all necessary occurrences

Yes, I didn't find inconsistencies any more.
