### ISSUE TITLE
Request following a Release message

### ISSUE THREAD

**Issue by jimsch** [core-wg/coap-tcp-tls#191]
What is the correct behavior if a peer sends a release message followed by a request?  Possible answers are:

1.  Ignore the request
2.  Stop processing the release

**Comment by cabo** [comment]
The text states that the peer receiving the release may close after having answered "requests received by it before the Release message".  If that peer is sending another request down the line, it cannot expect that to be handled, so 1 would seem to be right.  There is no indication that a new request stops processing the release, so 2 is not supported by the text.

We could add language that prohibits sending another request after sending a release (or an abort).

**Comment by jimsch** [comment]
I think adding the clarification would be reasonable

**Comment by hannestschofenig** [comment]
If a peer sends a release message I would assume that the logical thing is to assume that subsequent requests are not honored. We closed a few previously raised issues saying that the draft shouldn't state the obvious. If we provide clarifications here then I believe we should also provide clarifications to other issues as well to be fair to those raising the comments.
