### ISSUE TITLE
Not sure why the options/payload lengths have the minus XXX

### ISSUE THREAD

**Issue by lauri-piikivi** [core-wg/coap-tcp-tls#21]
Hi,

Is there an error, or is there a reason why the longer lengths are calculated with minus N bytes. The length field is always followed by code and token. What is the reason that e.g. 269 bytes would be subtracted from the option/payload length? The message header fixed length can be calculated from token length, so the option/payload length could be MAX unsigned 16-bit? 
 
13:
: An 8-bit unsigned integer follows the initial byte and indicates
  the length of options/payload minus 13.

14:
: A 16-bit unsigned integer in network byte order follows the
  initial byte and indicates the length of options/payload minus
  269.

15:
: A 32-bit unsigned integer in network byte order follows the
  initial byte and indicates the length of options/payload minus
  65805.

**Comment by cabo** [comment]
lauri piikivi wrote:
> Hi,
> 
> Is there an error, or is there a reason why the longer lengths are
> calculated with minus N bytes. The length field is always followed by
> code and token. What is the reason that e.g. 269 bytes would be
> subtracted from the option/payload length? 

This was modeled after the equivalent length encoding in the CoAP
options.  Will enable code reuse.

(The reason for that CoAP option length encoding is to simplify
achieving interoperability as there is only one encoding for each number.)

Grüße, Carsten

**Comment by brianraymor** [comment]
@lauri-piikivi - are there any further questions/suggestions on the encoding? If not, would you close?

**Comment by lauri-piikivi** [comment]
well, to me it seems strange. I doubt the code will be re-used. I would see that the parsing is done for the header separately (over UDP and over TCP), and options parsing which is common is it's own function and will understand the length field encoding better. I would propose that the message length is encoded normally.

**Comment by cabo** [comment]
I'm sorry, but we have had this discussion a while ago.  Since this has been implemented (and even copied over into other specs), changing the length encoding again bears a high cost at this time.  Please justify such a high cost.

**Comment by lauri-piikivi** [comment]
ok, no biggie. closing.
