### ISSUE TITLE
Outline by transport or by connection flow?

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#24]
Currently, the draft separates out the main sections for CoAP over TCP and CoAP over WebSockets.  (URIs and IANA details are merged). After we complete the entire merge, Klaus suggests
that we review the material to see if it makes more sense (due to redundant material) to have something more like:

Opening Handshake
- CoAP+TCP
-CoAp+WebSockets

Message Format
- CoAP+TCP
-CoAp+WebSockets

I definitely agree that sections like message transmission are redundant. Other sections like message format are quite different. It may be confusing for readers if TCP message format was followed by WebSockets message format - almost but entirely unlike.

**Comment by cabo** [comment]
The "opening handshake" (I don't think there such a thing -- we don't have a handshake) uses the message format, so I'm not sure this is the right sequence.  Generally I think that the question "how do we map CoAP to the underlying byte stream or WebSocket packet stream" needs to be answered before we add protocol (signaling messages).  The way some of the underlying protocol mechanisms (TCP options, TLS extensions, WebSockets ping/pong etc.) can be used in place of these signaling messages of course is specific to the underlying protocol being used; maybe it works best to fork these out under the specific functions that we try to achieve.  So maybe:

Message format

Signaling messages (the concept, not the specific messages)

Capability indication and Settings

Ping/pong, keep alive

Connection teardown and error handling

**Comment by brianraymor** [comment]
If there was a CSM exchange at the beginning of the connection per #16 or #20, then that would constitute part of the opening handshake.

**Comment by brianraymor** [comment]
Agreed on the 7/6 call with authors that the outline _by transport_ was acceptable.
