### ISSUE TITLE
Informative reference to cocoa

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#31]
In #28, there was a dissent about whether a cocoa reference is needed. I'm capturing the text. If cocoa is adopted as a working group item, then we can discuss adding before WGLC.

informative:
  ~~I-D.bormann-core-cocoa: cocoa~~

And from the Introduction:

_Some environments may also benefit from the ability of TCP to exchange larger payloads, such as firmware images, without application layer segmentation and to utilize the more sophisticated congestion control capabilities provided by many TCP implementations._

~~_Note that there is ongoing work to add more elaborate congestion control to CoAP as well, see {{-cocoa}}.)_~~

**Comment by hannestschofenig** [comment]
I am OK with your proposed resolution of adding a reference back into the document to CoCoA if it gets adopted as a WG item in the CORE WG sounds reasonable.

**Comment by brianraymor** [comment]
Closed by #67
