### ISSUE TITLE
Should Application Layer Protocol Negotiation (ALPN) always be required

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#4]
Captured from [Ticket 387](https://trac.tools.ietf.org/wg/core/trac/ticket/387), @cabo wrote:

Section 6.2 of says:

_When CoAP is exchanged over TLS port 443 then the "TLS Application Layer Protocol Negotiation Extension" [RFC7301] MUST be used to allow demultiplexing at the server-side unless out-of-band
 information ensures that the client only interacts with a server that is able to demultiplex CoAP messages over port 443. This would, for example, be true for many IoT deployments where clients are pre-configured to only ever talk with specific servers._

QUESTION: Shouldn't we simply always require ALPN? The protocol should not be defined in such a way that it depends on some undefined pre-configuration mechanism. --cabo

**Comment by brianraymor** [comment]
@cabo wrote:

The rough consensus appears that we should always require ALPN.

However, some TLS implementations do not provide ALPN. To accommodate these, we could make the exception that ALPN="coap" is implied on TLS over TCP, port 5684 only.

(This has no impact on the default port, which stays 443 for ​coaps+tcp://.)

(Idea: Klaus Hartke)

**Comment by brianraymor** [comment]
kovatsch@inf.ethz.ch commented:
The actual question is, will ALPN be implemented once we have a new version that must be indicated. If ALPN is not implemented, why should we solve cross-protocol attacks for them?

**Comment by brianraymor** [comment]
@cabo wrote:

One would hope that by the time we need a CoAP v2 (if ever), everybody will have ALPN, so no *new* workaround will then needed.

There seem to be good arguments to go with the exception for 5684 and require ALPN everywhere else.
This ticket will be closed unless new aspects come up.

**Comment by brianraymor** [comment]
Do we want to include a version in the encoding [similar to HTTP and SPDY?](http://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids)

**Comment by cabo** [comment]
While this is a bike shed question (there is no "right" answer), the general consensus so far was that we can add a version to the ALPN tag if it ever comes to a new version.  I.e., start with "coap" now, and move to "coapv2" or "coap2" if and when that is actually needed.  (We can also do version negotiation inside the signaling protocol, and depending on the characteristics of any new version, that may be more appropriate e.g. if a specific parameter also needs to be indicated/agreed.)

**Comment by cabo** [comment]
Room consensus in Berlin at IETF 96

**Comment by brianraymor** [comment]
To clarify, there was consensus to support ALPN with the _well-known_ 5684 exception.

**Comment by brianraymor** [comment]
Correcting a point made during the WG discussion - HTTP/2 **always** requires ALPN even when [Starting HTTP/2 with Prior Knowledge](https://tools.ietf.org/html/rfc7540#section-3.4):

_A client can learn that a particular server supports HTTP/2 by other means.  For example, [ALT-SVC] describes a mechanism for advertising this capability._

_A client MUST send the connection preface (Section 3.5) and then MAY immediately send HTTP/2 frames to such a server; servers can identify these connections by the presence of the connection preface.  **This only affects the establishment of HTTP/2 connections over cleartext TCP; implementations that support HTTP/2 over TLS MUST use protocol negotiation in TLS [TLS-ALPN].**_
