### ISSUE TITLE
Length of uint options

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#41]
sig-02 did not define the length for options with uint values. Can you confirm whether 0-4 is correct? I note that there are variants in the RFC7252 options with uint values.

**Comment by cabo** [comment]
Good catch.

0-4 definitely is right for Max-Message-Size.  0-4 is a bit over the top for Hold-Off, but arbitrarily limiting the time at, say, 65535 seconds (0-2) or 16777215 seconds (0-3) doesn't sound right either -- well, maybe half a year max (0-3) is about right.  Option numbers are 65535 max, so Bad-CSM-Option needs to be 0-2.
