### ISSUE TITLE
Clarifying "reliable transports"

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/coap-tcp-tls#49]
Replacing "CoAP over TCP, TLS and Websockets" with "CoAP over reliable transports" is a good idea to reduce repetition. I feel it might be a good idea to clarify when we refer to reliable transports, that we actually refer to stream-based reliable transports. 

Datagram-based  reliable transports (eg DCCP, QUIC, etc) exist, which render the Message Framing layer in Figure 1 unnecessary. I'm not advocating that we run CoAP over QUIC, DCCP etc but perhaps clarification would be wise.

**Comment by brianraymor** [comment]
See also #7

**Comment by hannestschofenig** [comment]
I would add a note to the terminology section that CoAP over reliable transports refers to stream-based transport protocols, such as TCP.

**Comment by brianraymor** [comment]
Sounds reasonable:

_The term "reliable transport" only refers to stream-based transport protocols such
as TCP._

**Comment by brianraymor** [comment]
https://www.ietf.org/mail-archive/web/core/current/msg08091.html

_The term "reliable transport" only refers to stream-based transport protocols such as TCP._

We could say more explicitly: sequenced/order-preserving, reliable... (Stream might be byte stream or message stream.)

**Comment by brianraymor** [comment]
@cabo - I would probably avoid "sequenced" which suggests sequence numbers and acknowledgements which are the mechanism to provide reliability. Perhaps too much detail?

How about:

The term "reliable transport" is used only to refer to transport protocols such as TCP which provide reliable and ordered delivery of a byte-stream.

**Comment by bsilverajan** [comment]
@cabo wrote: 

> The term "reliable transport" is used only to refer to transport protocols such as TCP which provide reliable and ordered delivery of a byte-stream.

This concisely clarifies my initial concern, and I'm ok with this.
