### ISSUE TITLE
Observing resource over reliable transports

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#5]
Captured from [Ticket 393](https://trac.tools.ietf.org/wg/core/trac/ticket/393): 

There needs to be a section on how resources can be observed over TCP/TLS. Questions include:

- Do servers need to include a sequence number in notifications, given that TCP/TLS provides reliable, in-order delivery? 
- How do servers throttle the stream of notifications when the resource changes its state more frequently than the server can send notifications? 
- Does a client have to re-register its interest in a resource if it hasn't received a notification for a while but the connection is still up?

**Comment by brianraymor** [comment]
https://trac.tools.ietf.org/wg/core/trac/ticket/393#comment:1

In a conference call with Klaus, Simon, Bill and myself we discussed the issue and the raised questions. 



QUESTION 1: Do servers need to include a sequence number in notifications, given that TCP/TLS provides reliable, in-order delivery?

The text from the CoAP over Websockets could be re-used. Here is what it could say:

_Since the TCP provides ordered delivery of messages, the mechanism for reordering detection when observing resources [RFC7641] is not needed. The value of the Observe Option in notifications therefore MAY be empty on transmission and MUST be ignored on reception._

The Observe Option still has to be sent since it contains other information as well.

QUESTION 2: Does a client have to re-register its interest in a resource if it hasn't received a notification for a while but the connection is still up?

We believe it is enough to send keep-alive message for the CoAP over TCP draft  (as opposed to send a re-registration message when used over UDP).

QUESTION 3: How do servers throttle the stream of notifications when the resource changes its state more frequently than the server can send notifications?

TCP offers a flow control mechanism as a means for the receiver to govern the amount of data sent by the sender. This is functionality that can be re-used.

**Comment by brianraymor** [comment]
https://trac.tools.ietf.org/wg/core/trac/ticket/393#comment:2

(1) -- I agree with the proposed solution.

(2) -- we need text that empty messages are no-ops and can be used as a keep-alive mechanism.

(3) -- this is a problem that most applications that start using reliable streams run into. Early implementations sometimes ignore the need for proper flow control. That is not a reason to add more mechanism (that would also not be in those early implementations), but the solution should be to use the flow control mechanisms we already have. Maybe an LWIG document could have information about flow control support in implementations, e.g., ​http://www.w3.org/TR/websockets/#dom-websocket-bufferedamount

**Comment by brianraymor** [comment]
https://trac.tools.ietf.org/wg/core/trac/ticket/393#comment:3

Has someone thought about the following setup, that is, will it work with keep-alives only?

There is a cluster behind a load balancer. I client sets up a connection, is assigned to one node and starts observing. For some reason the node fails and through a fail-over strategy the client is handed over to another node. All further requests are answered transparently be the new node. However, the Observe relationship got lost...

**Comment by brianraymor** [comment]
https://trac.tools.ietf.org/wg/core/trac/ticket/393#comment:4

Subissue 1 is covered by the Websockets draft; close this when merged.

Subissue 2 is covered by text in the Websockets draft; the failover problem described can be addressed by proper implementation of failover. This may however be costly, so we should have some more discussion about this.

Subissue 3 is an implementation quality issue. Just don't implement stream-based without some flow control.

**Comment by brianraymor** [comment]
On the 7/6 call with the authors, @hannestschofenig agreed to review and determine whether all issues were addressed.

**Comment by brianraymor** [comment]
This issue does not include a question about the use of confirmable messages for notifications in [RFC7641](https://tools.ietf.org/html/rfc7641#section-3.5) to determine client aliveness and interest:

_A notification can be confirmable or non-confirmable ...  An acknowledgement message signals to the server that the client is alive and interested in receiving further notifications; **if the server does not receive an acknowledgement in reply to a confirmable notification, it will assume that the client is no longer interested and will eventually remove** the associated entry from the list of observers_

This is inappropriate for CoAP over reliable transports.

**Comment by cabo** [comment]
The phrasing is a bit unfortunate.  What is meant is "if the confirmable notification times out".  The same would be true in TCP -- if the connection times out, you remove the interests.  We could clarify this in a section of CoAP-TCP about the impact of no longer sending back and forth acknowledgements.

**Comment by brianraymor** [comment]
Discussing the scope of this issue with the authors. This probably needs a more complete treatment rather than small references like:

   _Since the TCP protocol provides ordered delivery of messages, the
   mechanism for reordering detection when observing resources [RFC7641]
   is not needed.  The value of the Observe Option in notifications MAY
   be empty on transmission and MUST be ignored on reception._

**Comment by hannestschofenig** [comment]
My reading of the discussion thread gives me the impression that we had closed the initial set of questions. The subsequently raised issue regarding the wording in RFC 7641 I am wondering whether there is any change needed. We definitely are not going to change RFC 7641. I personally don't think that the highlighted text from RFC7641 will be wrongly implemented. 

I would suggest to close issue#5.

**Comment by brianraymor** [comment]
@hannestschofenig - this would be closed by #63 - any comments on that pull request?
