### ISSUE TITLE
May a client immediately send messages after sending its CSM ...

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#58]
When I submitted the original pull request, I also posed a question on the [mailing list](https://www.ietf.org/mail-archive/web/core/current/msg07732.html) but did not receive a response.

_One open question is whether we want to allow a client to immediately send messages after sending its CSM without waiting for the server CSM. This would be similar to HTTP/2:_

https://tools.ietf.org/html/rfc7540#section-3.5

  To avoid unnecessary latency, clients are permitted to send
   additional messages to the server immediately after sending the client
   connection preface, without waiting to receive the server connection
   preface.  It is important to note, however, that the server
   connection preface SETTINGS frame might include parameters that
   necessarily alter how a client is expected to communicate with the
   server.  Upon receiving the SETTINGS frame, the client is expected to
   honor any parameters established.  In some configurations, it is
   possible for the server to transmit SETTINGS before the client sends
   additional frames, providing an opportunity to avoid this issue.

**Comment by juanjperez** [comment]
I support not blocking the device until the server CSM.  The server can choose to not process messages that are invalid (e.g. too large) and immediately follow up with the server CSM.  From the perspective of a cloud and gateway software provider, the CoAP (using TCP/TLS) server will usually be in the cloud or gateway and therefore usually not power constrained.  I may be missing other scenarios where a battery powered device is acting as a CoAP/TCP server.  Does anyone have plans for any of those scenarios?

**Comment by brianraymor** [comment]
@hannestschofenig  added a related comment to #55 (which is closed)
_From your message I understand that in HTTP/2 the client can send messages immediately without waiting for the server to respond either. To me it feels like we should be doing what has been done in the HTTP/2 case even though there is a risk that some problems occur when the client sends data in way that the server will subsequently not handle well. If that is the case, the client will have to re-send the data, I guess. For the currently defined options I don't see problems._
