### ISSUE TITLE
Supporting block-wise for larger block sizes 

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#6]
Captured from [Ticket 409](https://trac.tools.ietf.org/wg/core/trac/ticket/409):

CoAP has been designed to support small data transmissions. For device management it is, however, necessary to also deal with the transmission of larger payloads as well. Such larger payloads may be, for example, firmware/software updates. 

The maximum payload size of CoAP is determined by the length field of the length field provided in the UDP header. It is ~64KB. For practical purposes the usable payload size is, however, much smaller due to performance issues introduced by fragmentation provided at the IP layer and/or adaption layers. For this reason the block-wise transfer mechanism has been defined. 

Block-wise transfer is a mechanism that can be used to transfer larger payloads by chunking them into smaller parts (each part with a maximum size of 1024 bytes each). The block-wise transfer depends on CoAP and therefore uses the stop-and-wait defined in RFC 7252 (as a simple congestion control mechanism). The transfer of large payloads does, however, not block the transmission of other pending messages since they can easily be interleaved due to the nature of the block-wise transfer design. 

When large payloads are transferred by CoAP over TCP then a large transfer blocks any other requests unless multiple TCP connections are opened. The question is therefore what should the CoAP over TCP state regarding the use of multiple TCP connections? Using multiple TCP connection increases RAM requirements; a single TCP connection introduces head-of-line blocking. 

When CoAP over TCP is used with Block-wise transport in combination with BERT, see ​https://tools.ietf.org/html/draft-bormann-core-block-bert-00, then the previously described problem of large transfers that block other ongoing activities is (partially) mitigated. BERT changes the interpretation of the length information and changes it as a multiple of 1024 bytes (and thus increasing the size of the chunks).

The question is therefore whether CoAP over TCP should recommend the use of Block-wise Transfer for large file transfers and incorporate BERT into the CoAP over TCP draft.

(I would like to thank Achim Kraus for raising this issue during the OMA face-to-face meeting.)

**Comment by brianraymor** [comment]
https://trac.tools.ietf.org/wg/core/trac/ticket/409#comment:3
+1 for BERT
It is a really simple solution that allows for relative good throughput without head-of-line blocking.

**Comment by brianraymor** [comment]
https://trac.tools.ietf.org/wg/core/trac/ticket/409#comment:4
(We are now waiting for the consensus call to complete; if positive, we can close this ticket with the merge of BERT.)

**Comment by brianraymor** [comment]
Capturing [Section 4.1 Discussion](https://tools.ietf.org/html/draft-ietf-core-coap-tcp-tls-02#section-4.1) which does not belong in the draft:

## Discussion

One observation is that, over a reliable byte stream transport, the message
size limitations defined in
Section 4.6 of {{RFC7252}} are no longer strictly necessary.
Consenting [^how] implementations may want to interchange messages
with payload sizes larger than 1024 bytes, potentially also obviating the
need for the Block protocol {{-block}}.  It must be noted that
entirely getting rid of the block protocol is
not a generally applicable solution, as:

* a UDP-to-TCP gateway may simply not have the context to convert a
  message with a Block option into the equivalent exchange without any
  use of a Block option;
* large messages might also cause undesired head-of-line blocking;
* the 2-byte message length field causes another, larger upper bound to the
  message length.

{{-bert}} proposes to extend the block-wise transfer protocol to allow
for larger block sizes as are possible over TCP and TLS.

[^how]: There is currently no defined way to arrive at this consent.
{: source="cabo"}

The general assumption is therefore that the block protocol will
continue to be used over TCP, even if TCP-based applications
occasionally do exchange messages with payload sizes larger than desirable in UDP.

**Comment by cabo** [comment]
Indeed.  The signaling draft has a Max-Message-Size capability indication option, which answers the question how to arrive at the consent that larger messages can be sent (and of which size).  We also seem to be converging on adding a capability indication for the Block protocol itself (which would then probably include BERT, possibly gated on having a Max-Message-Size > 1152).

**Comment by cabo** [comment]
Maybe some of this text should be moving as a rationale to the definition of the Block-wise capability indication option.

**Comment by brianraymor** [comment]
Possibly. That's why I captured the text for the moment. There might be fragments which can be reused when integrating the related proposed features. I just prefer to keep discussions and notes outside of drafts.

**Comment by brianraymor** [comment]
The "rationale" text does appear in some (edited) form in #2 - so it appears that the discussion points were addressed. I've separately captured the remaining embedded questions.
