### ISSUE TITLE
Ping and Pong Messages: ... a single Pong message MUST be returned?

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#69]
In [Section 4.4 Ping and Pong Messages](https://tools.ietf.org/html/draft-ietf-core-coap-tcp-tls-05#section-4.4):

  _Upon receipt of a Ping message, a single Pong message is returned with the identical token._ 

This should be _**MUST** be returned_ ?

**Comment by cabo** [comment]
One of the problems with this MUST is that it is hard to verify -- the responder has any amount of time to do this.  But, yes, the intention is that responders do this (that's why it's phrased as a statement of fact right now).

**Comment by brianraymor** [comment]
And the timing is more complicated when the sender includes a Custody Option in its Ping message.

**Comment by brianraymor** [comment]
Potential solutions:

- No changes to the design.
- If the custody option is not set in the Ping, then the receiver SHOULD respond with a Pong as soon as is practical.

**Comment by brianraymor** [comment]
**2/1 Conference call with Signaling authors**

Consensus to adopt proposal from @cabo :

_If we go that way, we should enable future options to maybe also have delaying semantics; so the SHOULD should apply to a PING with no such option (including no Custody option)._

_"Respond as soon as practical, unless there is an option with delaying semantics, such as Custody"_
