### ISSUE TITLE
Reliable transports for the Constrained Application Protocol (CoAP)

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#7]
With the merge of websockets-07, the scope of coap-tcp-tls is extended to include CoAP over WebSockets. The draft title should reflect that change in scope.

**Comment by cabo** [comment]
I probably would stay explicit (but then I'm biased -- RFC 3095 :-)

CoAP (Constraint Application Protocol) over TCP, TLS, and WebSockets

**Comment by brianraymor** [comment]
WFM.

**Comment by brianraymor** [comment]
Neglected to close with #9
