### ISSUE TITLE
UDP-to-TCP gateways

### ISSUE THREAD

**Issue by juanjperez** [core-wg/coap-tcp-tls#70]
Consider either removing the UDP to TCP gateway section (https://tools.ietf.org/html/draft-ietf-core-coap-tcp-tls-05#section-2.2) or merging into another section as an example.  Given the differences in message format in UDP vs TCP, this is a topic that may be useful as an example, but left as an implementation detail of a gateway.

**Comment by brianraymor** [comment]
Good point - in Hannes's earlier draft, this was more of an example than a separate section - https://tools.ietf.org/html/draft-tschofenig-core-coap-tcp-tls-05#section-3:

   _A UDP-to-TCP gateway will therefore discard all empty messages, such as
   empty ACKs (after operating on them at the message layer), and re-
   pack the contents of all non-empty CON, NON, or ACK messages (i.e.,
   those ACK messages that have a piggy-backed response) into untyped
   messages (that happen to look like NON messages)._

**Comment by brianraymor** [comment]
Closed by #92
