### ISSUE TITLE
Security Considerations: older versions of TLS

### ISSUE THREAD

**Issue by brianraymor** [core-wg/coap-tcp-tls#8]
_CoAP MUST NOT be used with older versions of TLS. Guidelines for use of cipher suites and TLS extensions can be found in {{I-D.ietf-dice-profile}}._

This should be phrased in the positive:

_Implementations of CoAP MUST use TLS version 1.2 or higher for CoAP over TLS. The general TLS usage guidance in [TLSBCP] SHOULD be followed ..._

What is the appropriate behavior when an older version is used?

For example, compare with [HTTP/2 TLS 1.2 Features](https://tools.ietf.org/html/rfc7540#section-9.2.1) for possible connection errors and further TLS 1.2 restrictions. 

_An endpoint MAY immediately terminate an HTTP/2 connection that does not meet these TLS requirements with a connection error of type INADEQUATE_SECURITY._

**Comment by cabo** [comment]
One interesting question is how TSL libraries export that functionality -- can a listener be configured to only allow 1.2+?  Is the actual protocol chosen signaled up?

**Comment by cabo** [comment]
https://github.com/ssllabs/ssllabs-scan/issues/258

**Comment by cabo** [comment]
http://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1

**Comment by brianraymor** [comment]
This may a case where an Inadequate-Security option could be added to Abort (Signaling)?

**Comment by cabo** [comment]
Right. Generally we should create machinery only where the recipient of some information can react to it in a programmatic way.  I don't expect a client to be automatically able to set up a new connection with a better TLS version upon reception of such an Inadequate-Security option.  So I think this is better handled in a diagnostic payload, which we don't need to standardize.
